### ISSUE TITLE
Proper exception handling

### ISSUE THREAD

**Issue by tairoman** [Titanothere/chathack#1]
# Exceptions

[How do exceptions work in Python?](https://docs.python.org/3/tutorial/errors.html) 
[Example of exception handling with sockets](http://www.java2s.com/Code/Python/Network/ErrorHandlingExample.htm)
[What do the socket exceptions mean?](https://docs.python.org/3/library/socket.html#exceptions)

These exceptions should be handled in order to create a safe and robust application. The TODO list has several cases of unsafe calls that should be solved. If I have forgotten any instances where exceptions may occur, please handle them too. 
### TODO List
- [ ] `socket.socket()` may give `socket.error` in client.py and server.py.
- [ ] `self.sock.connect(self.address)` may give `socket.error` in client.py due to connection error.
- [ ] `self.sock.connect(self.address)` may give `socket.gaierror` in client.py due to address related issues.
- [ ] All `send` methods and functions may give `socket.error` due to error sending data. 
- [ ] All `receive` and `recv` methods and functions may give `socket.error` due to error receiving data.
